### ISSUE TITLE
Database Seeding

### ISSUE THREAD

**Issue by olohr** [Campus-Consult/Personaltool#27]
- Hinzufügen von Default Daten für Posten/Status
- Hinzufügen von zufällig generierten Personen etc. zum testen

**Comment by Yorreck** [comment]
https://docs.microsoft.com/de-de/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-3.1&tabs=visual-studio#seed-the-database

**Comment by Yorreck** [comment]
could you implement two different kinds of seedings? One for sample datas for development and one for something like "factory settings". Espacially the memberstatus will be constant options so we do not need a configuration UI. The default configuration could be applied with a seeding
