### ISSUE TITLE
Models für Posten erstellen

### ISSUE THREAD

**Issue by Yorreck** [Campus-Consult/Personaltool#9]
- [x] Erzeugen des Models Models/Position.cs mit folgenden Attributen:
    - [x] + PositionID: int
    - [x] + Name: string
    - [x] + ShortName: string
    - [x] + IsActive: boolean
    - [x] + PersonsPositions: ICollection<PersonsPosition>
    - [x] Hinzufügen von Validierungsregeln (Vergleich [hier](https://docs.microsoft.com/de-de/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-3.1))

----

- [x] Erzeugen des Models Models/PersonsPosition.cs mit folgenden Attributen:
    - [x] + PersonsPositionID: int
    - [x] + PersonID: int
    - [x] + PositionID: int
    - [x] + Begin: DateTime (Date)
    - [x] + End: DateTime (Date)
    - [x] + Person: Person
    - [x] + Position: Position
    - [x] Hinzufügen von Validierungsregeln (Vergleich [hier](https://docs.microsoft.com/de-de/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-3.1))

----

- [x] Attribut dem Model Models/Person.cs hinzufügen:
    - [x] + PersonsPositions: ICollection<PersonsPosition>

----

- [x] DbSet in Data/ApplicationDbContext.cs anlegen
    - [x] DbSet<Position> Positions
    - [x] DbSet<PersonsPosition> PersonsPositions
    - [x] Erstelle eine Migration:
        - `dotnet ef migrations add <hier einen namen wählen>`
        - `dotnet ef database update`

**Comment by LTobor** [comment]
Benötigen Namen oder auch Kurznamen generell eine Validierung [DisplayType(DisplayType.Text)] ? Ich gehe erst einmal davon aus, dass dieses bei der allgemeinen Bezeichnung sinnvoll ist, jedoch bei der Kurzbeschreibung alles zugelassen ist.
@Yorreck @olohr
